# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# RasCal.py
# Created on: 2014-09-09 15:00:31.00000
#   (generated by Koech Nicholas, RS/GIS Analyst - CIAT)
# Description: Script coded to generate NDVI by maximum value composite
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy
from arcpy import env
from arcpy.sa import *


class ModisNDVICalc(object):
    """Search for MODIS .tif file and calculate mean raster using ArcGIS Cell Statistics"""

    def get_file_paths(self):
        """Returns MODIS file paths"""
        tiff_dirs = []
        counter = 0
        for root_path, dir_names, files in os.walk("D:\\Data\\Modis"):
            for dir_name in dir_names:
                for dir_Output in dir_name.split("_"):
                    if dir_Output == "TIFF":
                        dir_join = os.path.join(root_path, dir_name).replace("\\","/")
                        tiff_dirs.append(dir_join)
        return tiff_dirs

    def gen_ndvi(self):
        """Generate NDVI from raster images using ArcGIS map algebra"""
        for source_path in self.get_file_paths():
            counter = 0
            for file in os.listdir(source_path):
                if file.startswith('MOD_') & file.endswith('.tif'):
                    counter += 1
                    file_path = os.path.join(source_path, file).replace("\\","/")
                    out_ras = source_path + "/NDVI_MOD_" + file[-16:]
                    print("GENERATING NDVI FOR ......... " + file)
                    mod_ndvi = Con((Raster(file_path) * 0.0001) >=  - 1.0, (Raster(file_path) * 0.0001), "")
                    mod_ndvi.save(out_ras)
        print("NDVI GENERATION COMPLETED!!!")

    def gen_mvc_ndvi(self):
        """Get files and calculate Maximum Value using cell statistics gp"""
        for source_path in self.get_file_paths():
            ras_input = []
            for file in os.listdir(source_path):
                if file.startswith('NDVI_') & file.endswith('.tif'):
                    file_path = os.path.join(source_path, file).replace("\\","/")
                    ras_input.append(file_path)
            out_ras = source_path + "/MVC_MOD_NDVI_" + source_path[-4:] + ".tif"
            print("GENERATING MVC FOR ......... " + source_path[-4:])
            arcpy.gp.CellStatistics_sa(ras_input, out_ras, "MAXIMUM", "DATA")
        print("MVC GENERATION COMPLETED!!!")

def main():
    """Main program"""
    # Check out any necessary licenses
    env.overwriteOutput = True
    arcpy.CheckOutExtension("spatial")
    vi_Calc = ModisNDVICalc()
    vi_Calc.gen_ndvi()
    vi_Calc.gen_mvc_ndvi()

if __name__ == "__main__":
    main()
    




